### ISSUE TITLE
Errno::EACCES: Permission denied @ rb_sysopen

### ISSUE THREAD

**Issue by zwarburg** [basecamp/marcel#10]
Been trying to install this gem as part of a rails app and I keep getting the following error...
```
Errno::EACCES: Permission denied @ rb_sysopen -
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/marcel-0.3.2/test/fixtures/magic/video/quicktime/quicktime.mov
An error occurred while installing marcel (0.3.2), and Bundler cannot continue.
Make sure that `gem install marcel -v '0.3.2' --source 'https://rubygems.org/'`
```
I have full access to the folder so I'm mighty confused.

**Comment by jeremy** [comment]
Looks like a RubyGems issue: https://github.com/rubygems/rubygems/issues/1784 https://bugs.ruby-lang.org/issues/13151

(Tangentially, we needn't be shipping test fixtures with gem releases!)

**Comment by zwarburg** [comment]
@jeremy any idea how I can resolve the issue?

**Comment by jeremy** [comment]
I’m not personally familiar with the issue beyond this, sorry! I’d dig
further into the bug reports above and see whether the suggested fixes work
for you, or use them as a starting point for your own troubleshooting.
