### ISSUE TITLE
Consider removing tests from the distribution

### ISSUE THREAD

**Issue by mvz** [basecamp/marcel#13]
The actual code of this gem is very small, but the gem takes up more than 10MB due to the tests fixtures. Please consider removing the tests from the distributed gem.

For some background: https://github.com/rubygems/rubygems/issues/735

**Comment by jeremy** [comment]
Agreed. Pull request welcome 👍

**Comment by georgeclaghorn** [comment]
Already done in #11. Upgrade to [0.3.3](https://github.com/basecamp/marcel/releases/tag/v0.3.3).
